blank_issues_enabled: false
contact_links:
  - name: Paddle support
    url: https://www.paddle.com/help
    about: |
      Please only open issues here that you believe represent actual bugs or feature requests for the Paddle PHP SDK.

      For help with the Paddle API or building your integration, contact our support team at sellers@paddle.com.